sudo: required
langauge: generic

services:
  - docker

before_install:
  - docker build -t sulinys/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sulinys/multi-docker npm run test -- --coverage

after_success:
  - docker build -t sulinys/multi-client ./client
  - docker build -t sulinys/multi-nginx ./nginx
  - docker build -t sulinys/multi-server ./server
  - docker build -t sulinys/multi-worker ./worker
  #docker push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin  
  - docker push sulinys/multi-client
  - docker push sulinys/multi-nginx
  - docker push sulinys/multi-server
  - docker push sulinys/multi-worker  


# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: "multi-docker"
#   env: "Dockerreact-env"
#   bucket_name: "elasticbeanstalk-us-east-1-924592818002"
#   bucket_path: "multi-docker"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY